### PR TITLE
BUG: Correctly set 'Live' mode

### LINKED ISSUE #10: VersionedReadingMode::setLiveReadingMode() erroneously sets the mode to 'Stage'.
A pull request is forthcoming.

### PR DESCRIPTION
**Pull request by oddnoc**
Fixes #10.

### CODE REVIEW

**Comment by glenn-bautista** [comment]
Thanks heaps for correcting this oversight

**Comment by camspiers** [comment]
The previous code probably should have gone through code review.

**Comment by glenn-bautista** [comment]
@camspiers I agree. Unfortunately we don't have the resources to do that, hence the second best approach, open source which did save the day today.

**Comment by camspiers** [comment]
This is an open source project, it doesn't have much to do with what resources Heyday has. You can create a pull request to the open-source project instead of push straight to master. Feel free to cc me, and I am sure @stevie-mayhew wouldn't mind either.

**Pull request merged**
