### PR TITLE
Added ability to manipulate the edit form

### PR DESCRIPTION
**Pull request by tylerkidd**
Added ability to manipulate the edit form. Sometimes you need to add additional actions, or manipulate form fields that might be getting added or manipulated through this module.

```	
public function updateItemEditForm($form) {
    $actions = $form->getActions();
    $record = $form->getRecord();
    
    if($record->doCheckSomething()){
        $actions->removeByName('action_unpublish');
    }
}
```

### CODE REVIEW

**Comment by stecman** [comment]
If there's no conflict, `updateItemEditForm` would be better than `updateVersionedItemEditForm`, as it mirrors the parent class's extend API.

Also, can you squash these commits please?

**Comment by tylerkidd** [comment]
That's where I started, but immediately had an issue where it was being called multiple times. Might just be due to my current setup - but I just thought this might allow you to be more contextually specific. Let me know what you think and I'll make the change + squash the extra commit where I made that change.

**Comment by tylerkidd** [comment]
I changed it back to updateItemEditForm. Should be good to go now?

**Comment by stecman** [comment]
Did that end up working for your code with `updateItemEditForm`? In theory most field operations should be repeatable without causing any problems. Anyone have any objections to this?

**Comment by tylerkidd** [comment]
Yeah, it did! I found that another module was being somewhat greedy with i t's usage of updateItemEditForm and completely throwing off everything I was setting elsewhere.

**Pull request merged**
