### PR TITLE
Added namespaces

### PR DESCRIPTION
**Pull request by assertchris**
Reference: https://github.com/heyday/silverstripe-versioneddataobjects/issues/17

### CODE REVIEW

**Comment by stecman** [comment]
Thanks for sorting this, Chris. Have you run the module with these changes, or just gone through and added the namespaces?

**Comment by assertchris** [comment]
@stecman running it on a site we're developing (sorry, can't say which yet), and it's working like a charm. I may find time to make a few behat tests but for now it appears to be working...

**Comment by stecman** [comment]
Great, thanks. I'll merge and release this as 2.0.0. The readme can be updated separately. 👍

**Comment by camspiers** [comment]
Who's the best? @assertchris is.

**Comment by MattyBalaam** [comment]
What are the SilverStripe requirements using this update?

**Pull request merged**
